// Topic-typesofoperator

// opearator-Used to perform some operation on data




// 1.Arithmetic Operators
// +, -, *, /


// Modulus-%
// Exponentiation-**-power
// Increment-++
// Decrement- --


let a = 5;
let b = 2;
// 1.plus
console.log("a=", a , "& b=", b);
console.log("a+b=",a+b,);
// 2. minus/deduction
console.log("a-b=",a-b);
// 3.multiply
console.log("a*b=",a*b);
// 4.divide or slash
console.log("a/b=",a/b);

// additional operator

// *modules*_%-reminder value - in modules we print reminder value
console.log("a%b=",a%b);

// *Expontiation*_**_power like 2**2=4_second sign_^

console.log("a**b=",a**b);


// Increment/Decrement - we also called unary operator

// *Increment*_a++, a+1-both are same like a=5, a++=6, a+1=6
//  ++a - prefix -first increment the value then assigning the value; for ex=6
//  a++ - postfix - first assign the value then incremrnt the value

let c = 20

console.log("++c=",++c);
console.log("c++=", c++);
console.log(c)

let d = 15;
console.log(d);
console.log(++d);
console.log(d++);
console.log(d);










